### ISSUE TITLE
windows环境下getNodeExe的问题

### ISSUE THREAD

**Issue by hcfw007** [X-Profiler/xtransit#32]
首先感谢作者，在egg项目中我们使用过egg-xtransit插件，这一项目对我们有很大的帮助。
在试图将此功能扩展到一些非egg项目中，我遇到了一个问题，并且找到了原因。我认为这可能算是个bug。
系统: win10 20H2
Node: 16.13.0
https://github.com/X-Profiler/xtransit/blob/222eb1cfc66137cab73071d6ba86466ff513ce28/common/exe.js#L13-L58
在这一方法中，win32系统默认情况下，```executable```本身是一个string，stringify默认为true，于是```nodeExe = stringify ? JSON.stringify(executable) : executable;```会将一个string进行stringify，等于会往这个string外面套两个引号。即
```js
console.log(JSON.stringify('C:\\Program Files\\nodejs\\node.exe')) // "C:\\Program Files\\nodejs\\node.exe"
console.log('C:\\Program Files\\nodejs\\node.exe') // C:\\Program Files\\nodejs\\node.exe
```
而有引号的string在进行realpath的时候会报错，会被当做相对路径对待，然后等同于```realpath(`${ pwd }nodeExe`)```，报一个ENOENT错误。

**Comment by hcfw007** [comment]
由于windows下Program Files中间有空格，所以nodeExe的引号还是有用的。因此修改一下```const nodeExe = await realpath(await getNodeExe(process.pid));```这边就行。
#33

**Comment by hyj1991** [comment]
`xtransit@1.3.2` 已发布
