### ISSUE TITLE
可以自己指定进程ID吗

### ISSUE THREAD

**Issue by zjy01** [X-Profiler/xtransit#41]
```bash
Command failed: ps -e -o pid,args | grep -E "node |iojs |PM2 " | grep -v grep
```

我们的服务部署方式没有办法通过上面的方式获取到pid，我们能不能自己指定pid呢，或者修改匹配命令
```bash
    306 /usr/local/app/bin/src/dist/main.js: master process
    331 /usr/local/app/bin/src/dist/main.js: worker process
```

**Comment by hyj1991** [comment]
![image](https://user-images.githubusercontent.com/19908330/177684130-a6d15300-296d-4780-827f-e78e200ba4bf.png)

`xtransit` 这里有个 `titles` 字段，可以自定义自己 Node.js 的名称，看看是否可以满足你的需求？

**Comment by zjy01** [comment]
> ![image](https://user-images.githubusercontent.com/19908330/177684130-a6d15300-296d-4780-827f-e78e200ba4bf.png)
> 
> `xtransit` 这里有个 `titles` 字段，可以自定义自己 Node.js 的名称，看看是否可以满足你的需求？

有用，感谢
